version: "3.8"

services:
  gateway:
    networks:
      core:
    build:
      context: src/gateway
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      # - iam
      - finding
    environment:
      - PORT=8080
      - FINDING_SVC_ADDR=finding:8081
    ports:
      - "8080:8080"

  finding:
    networks:
      core:
    build:
      context: src/finding
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - PORT=8081
    ports:
      - "8081"

  # iam:
  #   networks:
  #     core:
  #   build: src/iam
  #     context: src/iam
  #     args:
  #       - GITHUB_USER=${GITHUB_USER}
  #       - GITHUB_TOKEN=${GITHUB_TOKEN}
  #   environment:
  #     - PORT=8082
  #   ports:
  #     - "8082"

networks:
  core:
    driver: bridge
    attachable: true
