syntax = "proto3";

package core.ai;
option go_package = "github.com/ca-risken/core/proto/ai";

import "validate/validate.proto";

/*
 * Entity
 */

// ChatHistory
message ChatHistory {
  ChatRole role = 1;
  string content = 2;
}

// ChatRole
enum ChatRole {
  CHAT_ROLE_UNSPECIFIED = 0;
  CHAT_ROLE_USER = 1;
  CHAT_ROLE_ASSISTANT = 2;
  CHAT_ROLE_SYSTEM = 3;
}

// RemediationProposal
message RemediationProposal {
  uint32 remediation_proposal_id = 1;
  uint64 finding_id = 2;
  uint32 project_id = 3;
  string status = 4;
  string status_detail = 5;
  string remediation_plan = 6; // JSON
  int64 generated_at = 7;
  int64 created_at = 8;
  int64 updated_at = 9;
}

// RemediationProposalForUpsert
message RemediationProposalForUpsert {
  uint32 remediation_proposal_id = 1;
  uint64 finding_id = 2;
  string status = 3 [ (validate.rules).string = {
    in : [ "PENDING", "SUCCEEDED", "FAILED" ]
  } ];
  string status_detail = 4;
  string remediation_plan = 5; // JSON
  int64 generated_at = 6;
}
