syntax = "proto3";

package core.ai;
option go_package = "github.com/ca-risken/core/proto/ai";

import "ai/entity.proto";
import "validate/validate.proto";

service AIService {
  rpc ChatAI(ChatAIRequest) returns (ChatAIResponse);
  rpc GenerateReport(GenerateReportRequest) returns (GenerateReportResponse);
  rpc GetRemediationProposal(GetRemediationProposalRequest)
      returns (GetRemediationProposalResponse);
  rpc PutRemediationProposal(PutRemediationProposalRequest)
      returns (PutRemediationProposalResponse);
  rpc ListRemediationProposal(ListRemediationProposalRequest)
      returns (ListRemediationProposalResponse);
}

message ChatAIRequest {
  string question = 1 [ (validate.rules).string.min_len = 1 ]; // Required
  repeated ChatHistory chat_history = 2;
  uint32 project_id = 3;
}

message ChatAIResponse { string answer = 1; }

message GenerateReportRequest {
  string prompt = 1 [ (validate.rules).string.min_len = 1 ]; // Required
  uint32 project_id = 2 [ (validate.rules).uint32.gt = 0 ];  // Required
  string name = 3 [ (validate.rules).string.min_len = 1 ];   // Required
}

message GenerateReportResponse {
  uint32 report_id = 1;
  string status = 2;
}

message GetRemediationProposalRequest {
  uint32 project_id = 1 [ (validate.rules).uint32.gt = 0 ]; // Required
  uint32 remediation_proposal_id = 2
      [ (validate.rules).uint32.gt = 0 ]; // Required
}

message GetRemediationProposalResponse {
  RemediationProposal remediation_proposal = 1;
}

message PutRemediationProposalRequest {
  uint32 project_id = 1 [ (validate.rules).uint32.gt = 0 ]; // Required
  uint32 remediation_proposal_id = 2;
  uint64 finding_id = 3 [ (validate.rules).uint64.gt = 0 ]; // Required
  string status = 4 [
    (validate.rules).string = {in : [ "PENDING", "SUCCEEDED", "FAILED" ]}
  ]; // Required
  string status_detail = 5;
  string remediation_plan = 6;
  int64 generated_at = 7;
}

message PutRemediationProposalResponse {
  RemediationProposal remediation_proposal = 1;
}

message ListRemediationProposalRequest {
  uint32 project_id = 1 [ (validate.rules).uint32.gt = 0 ]; // Required
  uint64 finding_id = 2 [ (validate.rules).uint64.gt = 0 ]; // Required
  repeated string status = 3 [ (validate.rules).repeated.items.string = {
    in : [ "PENDING", "SUCCEEDED", "FAILED" ]
  } ];
}

message ListRemediationProposalResponse {
  repeated RemediationProposal remediation_proposal = 1;
}
