// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: organization/service.proto

package organization

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListOrganizationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListOrganizationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListOrganizationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListOrganizationRequestMultiError, or nil if none found.
func (m *ListOrganizationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListOrganizationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrganizationId

	if utf8.RuneCountInString(m.GetName()) > 64 {
		err := ListOrganizationRequestValidationError{
			field:  "Name",
			reason: "value length must be at most 64 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for UserId

	// no validation rules for ProjectId

	if len(errors) > 0 {
		return ListOrganizationRequestMultiError(errors)
	}

	return nil
}

// ListOrganizationRequestMultiError is an error wrapping multiple validation
// errors returned by ListOrganizationRequest.ValidateAll() if the designated
// constraints aren't met.
type ListOrganizationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListOrganizationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListOrganizationRequestMultiError) AllErrors() []error { return m }

// ListOrganizationRequestValidationError is the validation error returned by
// ListOrganizationRequest.Validate if the designated constraints aren't met.
type ListOrganizationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListOrganizationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListOrganizationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListOrganizationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListOrganizationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListOrganizationRequestValidationError) ErrorName() string {
	return "ListOrganizationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListOrganizationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListOrganizationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListOrganizationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListOrganizationRequestValidationError{}

// Validate checks the field values on ListOrganizationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListOrganizationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListOrganizationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListOrganizationResponseMultiError, or nil if none found.
func (m *ListOrganizationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListOrganizationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetOrganization() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListOrganizationResponseValidationError{
						field:  fmt.Sprintf("Organization[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListOrganizationResponseValidationError{
						field:  fmt.Sprintf("Organization[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListOrganizationResponseValidationError{
					field:  fmt.Sprintf("Organization[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListOrganizationResponseMultiError(errors)
	}

	return nil
}

// ListOrganizationResponseMultiError is an error wrapping multiple validation
// errors returned by ListOrganizationResponse.ValidateAll() if the designated
// constraints aren't met.
type ListOrganizationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListOrganizationResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListOrganizationResponseMultiError) AllErrors() []error { return m }

// ListOrganizationResponseValidationError is the validation error returned by
// ListOrganizationResponse.Validate if the designated constraints aren't met.
type ListOrganizationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListOrganizationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListOrganizationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListOrganizationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListOrganizationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListOrganizationResponseValidationError) ErrorName() string {
	return "ListOrganizationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListOrganizationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListOrganizationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListOrganizationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListOrganizationResponseValidationError{}

// Validate checks the field values on CreateOrganizationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateOrganizationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateOrganizationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateOrganizationRequestMultiError, or nil if none found.
func (m *CreateOrganizationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateOrganizationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 64 {
		err := CreateOrganizationRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetDescription()); l < 0 || l > 255 {
		err := CreateOrganizationRequestValidationError{
			field:  "Description",
			reason: "value length must be between 0 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserId() <= 0 {
		err := CreateOrganizationRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateOrganizationRequestMultiError(errors)
	}

	return nil
}

// CreateOrganizationRequestMultiError is an error wrapping multiple validation
// errors returned by CreateOrganizationRequest.ValidateAll() if the
// designated constraints aren't met.
type CreateOrganizationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateOrganizationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateOrganizationRequestMultiError) AllErrors() []error { return m }

// CreateOrganizationRequestValidationError is the validation error returned by
// CreateOrganizationRequest.Validate if the designated constraints aren't met.
type CreateOrganizationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateOrganizationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateOrganizationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateOrganizationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateOrganizationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateOrganizationRequestValidationError) ErrorName() string {
	return "CreateOrganizationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateOrganizationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateOrganizationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateOrganizationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateOrganizationRequestValidationError{}

// Validate checks the field values on CreateOrganizationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateOrganizationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateOrganizationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateOrganizationResponseMultiError, or nil if none found.
func (m *CreateOrganizationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateOrganizationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOrganization()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateOrganizationResponseValidationError{
					field:  "Organization",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateOrganizationResponseValidationError{
					field:  "Organization",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOrganization()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateOrganizationResponseValidationError{
				field:  "Organization",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateOrganizationResponseMultiError(errors)
	}

	return nil
}

// CreateOrganizationResponseMultiError is an error wrapping multiple
// validation errors returned by CreateOrganizationResponse.ValidateAll() if
// the designated constraints aren't met.
type CreateOrganizationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateOrganizationResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateOrganizationResponseMultiError) AllErrors() []error { return m }

// CreateOrganizationResponseValidationError is the validation error returned
// by CreateOrganizationResponse.Validate if the designated constraints aren't met.
type CreateOrganizationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateOrganizationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateOrganizationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateOrganizationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateOrganizationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateOrganizationResponseValidationError) ErrorName() string {
	return "CreateOrganizationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateOrganizationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateOrganizationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateOrganizationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateOrganizationResponseValidationError{}

// Validate checks the field values on UpdateOrganizationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateOrganizationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateOrganizationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateOrganizationRequestMultiError, or nil if none found.
func (m *UpdateOrganizationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateOrganizationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOrganizationId() <= 0 {
		err := UpdateOrganizationRequestValidationError{
			field:  "OrganizationId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 64 {
		err := UpdateOrganizationRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetDescription()); l < 0 || l > 255 {
		err := UpdateOrganizationRequestValidationError{
			field:  "Description",
			reason: "value length must be between 0 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateOrganizationRequestMultiError(errors)
	}

	return nil
}

// UpdateOrganizationRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateOrganizationRequest.ValidateAll() if the
// designated constraints aren't met.
type UpdateOrganizationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateOrganizationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateOrganizationRequestMultiError) AllErrors() []error { return m }

// UpdateOrganizationRequestValidationError is the validation error returned by
// UpdateOrganizationRequest.Validate if the designated constraints aren't met.
type UpdateOrganizationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateOrganizationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateOrganizationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateOrganizationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateOrganizationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateOrganizationRequestValidationError) ErrorName() string {
	return "UpdateOrganizationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateOrganizationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateOrganizationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateOrganizationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateOrganizationRequestValidationError{}

// Validate checks the field values on UpdateOrganizationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateOrganizationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateOrganizationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateOrganizationResponseMultiError, or nil if none found.
func (m *UpdateOrganizationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateOrganizationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOrganization()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateOrganizationResponseValidationError{
					field:  "Organization",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateOrganizationResponseValidationError{
					field:  "Organization",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOrganization()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateOrganizationResponseValidationError{
				field:  "Organization",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateOrganizationResponseMultiError(errors)
	}

	return nil
}

// UpdateOrganizationResponseMultiError is an error wrapping multiple
// validation errors returned by UpdateOrganizationResponse.ValidateAll() if
// the designated constraints aren't met.
type UpdateOrganizationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateOrganizationResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateOrganizationResponseMultiError) AllErrors() []error { return m }

// UpdateOrganizationResponseValidationError is the validation error returned
// by UpdateOrganizationResponse.Validate if the designated constraints aren't met.
type UpdateOrganizationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateOrganizationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateOrganizationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateOrganizationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateOrganizationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateOrganizationResponseValidationError) ErrorName() string {
	return "UpdateOrganizationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateOrganizationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateOrganizationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateOrganizationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateOrganizationResponseValidationError{}

// Validate checks the field values on DeleteOrganizationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteOrganizationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteOrganizationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteOrganizationRequestMultiError, or nil if none found.
func (m *DeleteOrganizationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteOrganizationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOrganizationId() <= 0 {
		err := DeleteOrganizationRequestValidationError{
			field:  "OrganizationId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteOrganizationRequestMultiError(errors)
	}

	return nil
}

// DeleteOrganizationRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteOrganizationRequest.ValidateAll() if the
// designated constraints aren't met.
type DeleteOrganizationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteOrganizationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteOrganizationRequestMultiError) AllErrors() []error { return m }

// DeleteOrganizationRequestValidationError is the validation error returned by
// DeleteOrganizationRequest.Validate if the designated constraints aren't met.
type DeleteOrganizationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteOrganizationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteOrganizationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteOrganizationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteOrganizationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteOrganizationRequestValidationError) ErrorName() string {
	return "DeleteOrganizationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteOrganizationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteOrganizationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteOrganizationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteOrganizationRequestValidationError{}

// Validate checks the field values on ListProjectsInOrganizationRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ListProjectsInOrganizationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListProjectsInOrganizationRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ListProjectsInOrganizationRequestMultiError, or nil if none found.
func (m *ListProjectsInOrganizationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListProjectsInOrganizationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOrganizationId() <= 0 {
		err := ListProjectsInOrganizationRequestValidationError{
			field:  "OrganizationId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListProjectsInOrganizationRequestMultiError(errors)
	}

	return nil
}

// ListProjectsInOrganizationRequestMultiError is an error wrapping multiple
// validation errors returned by
// ListProjectsInOrganizationRequest.ValidateAll() if the designated
// constraints aren't met.
type ListProjectsInOrganizationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListProjectsInOrganizationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListProjectsInOrganizationRequestMultiError) AllErrors() []error { return m }

// ListProjectsInOrganizationRequestValidationError is the validation error
// returned by ListProjectsInOrganizationRequest.Validate if the designated
// constraints aren't met.
type ListProjectsInOrganizationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListProjectsInOrganizationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListProjectsInOrganizationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListProjectsInOrganizationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListProjectsInOrganizationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListProjectsInOrganizationRequestValidationError) ErrorName() string {
	return "ListProjectsInOrganizationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListProjectsInOrganizationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListProjectsInOrganizationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListProjectsInOrganizationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListProjectsInOrganizationRequestValidationError{}

// Validate checks the field values on ListProjectsInOrganizationResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ListProjectsInOrganizationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListProjectsInOrganizationResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ListProjectsInOrganizationResponseMultiError, or nil if none found.
func (m *ListProjectsInOrganizationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListProjectsInOrganizationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetProject() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListProjectsInOrganizationResponseValidationError{
						field:  fmt.Sprintf("Project[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListProjectsInOrganizationResponseValidationError{
						field:  fmt.Sprintf("Project[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListProjectsInOrganizationResponseValidationError{
					field:  fmt.Sprintf("Project[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListProjectsInOrganizationResponseMultiError(errors)
	}

	return nil
}

// ListProjectsInOrganizationResponseMultiError is an error wrapping multiple
// validation errors returned by
// ListProjectsInOrganizationResponse.ValidateAll() if the designated
// constraints aren't met.
type ListProjectsInOrganizationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListProjectsInOrganizationResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListProjectsInOrganizationResponseMultiError) AllErrors() []error { return m }

// ListProjectsInOrganizationResponseValidationError is the validation error
// returned by ListProjectsInOrganizationResponse.Validate if the designated
// constraints aren't met.
type ListProjectsInOrganizationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListProjectsInOrganizationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListProjectsInOrganizationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListProjectsInOrganizationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListProjectsInOrganizationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListProjectsInOrganizationResponseValidationError) ErrorName() string {
	return "ListProjectsInOrganizationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListProjectsInOrganizationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListProjectsInOrganizationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListProjectsInOrganizationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListProjectsInOrganizationResponseValidationError{}

// Validate checks the field values on RemoveProjectsInOrganizationRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *RemoveProjectsInOrganizationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoveProjectsInOrganizationRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// RemoveProjectsInOrganizationRequestMultiError, or nil if none found.
func (m *RemoveProjectsInOrganizationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoveProjectsInOrganizationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOrganizationId() <= 0 {
		err := RemoveProjectsInOrganizationRequestValidationError{
			field:  "OrganizationId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetProjectId() <= 0 {
		err := RemoveProjectsInOrganizationRequestValidationError{
			field:  "ProjectId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RemoveProjectsInOrganizationRequestMultiError(errors)
	}

	return nil
}

// RemoveProjectsInOrganizationRequestMultiError is an error wrapping multiple
// validation errors returned by
// RemoveProjectsInOrganizationRequest.ValidateAll() if the designated
// constraints aren't met.
type RemoveProjectsInOrganizationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoveProjectsInOrganizationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoveProjectsInOrganizationRequestMultiError) AllErrors() []error { return m }

// RemoveProjectsInOrganizationRequestValidationError is the validation error
// returned by RemoveProjectsInOrganizationRequest.Validate if the designated
// constraints aren't met.
type RemoveProjectsInOrganizationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveProjectsInOrganizationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveProjectsInOrganizationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveProjectsInOrganizationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveProjectsInOrganizationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveProjectsInOrganizationRequestValidationError) ErrorName() string {
	return "RemoveProjectsInOrganizationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveProjectsInOrganizationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveProjectsInOrganizationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveProjectsInOrganizationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveProjectsInOrganizationRequestValidationError{}

// Validate checks the field values on ListOrganizationInvitationRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ListOrganizationInvitationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListOrganizationInvitationRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ListOrganizationInvitationRequestMultiError, or nil if none found.
func (m *ListOrganizationInvitationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListOrganizationInvitationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrganizationId

	// no validation rules for ProjectId

	if len(errors) > 0 {
		return ListOrganizationInvitationRequestMultiError(errors)
	}

	return nil
}

// ListOrganizationInvitationRequestMultiError is an error wrapping multiple
// validation errors returned by
// ListOrganizationInvitationRequest.ValidateAll() if the designated
// constraints aren't met.
type ListOrganizationInvitationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListOrganizationInvitationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListOrganizationInvitationRequestMultiError) AllErrors() []error { return m }

// ListOrganizationInvitationRequestValidationError is the validation error
// returned by ListOrganizationInvitationRequest.Validate if the designated
// constraints aren't met.
type ListOrganizationInvitationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListOrganizationInvitationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListOrganizationInvitationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListOrganizationInvitationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListOrganizationInvitationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListOrganizationInvitationRequestValidationError) ErrorName() string {
	return "ListOrganizationInvitationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListOrganizationInvitationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListOrganizationInvitationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListOrganizationInvitationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListOrganizationInvitationRequestValidationError{}

// Validate checks the field values on ListOrganizationInvitationResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ListOrganizationInvitationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListOrganizationInvitationResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ListOrganizationInvitationResponseMultiError, or nil if none found.
func (m *ListOrganizationInvitationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListOrganizationInvitationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetOrganizationInvitations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListOrganizationInvitationResponseValidationError{
						field:  fmt.Sprintf("OrganizationInvitations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListOrganizationInvitationResponseValidationError{
						field:  fmt.Sprintf("OrganizationInvitations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListOrganizationInvitationResponseValidationError{
					field:  fmt.Sprintf("OrganizationInvitations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListOrganizationInvitationResponseMultiError(errors)
	}

	return nil
}

// ListOrganizationInvitationResponseMultiError is an error wrapping multiple
// validation errors returned by
// ListOrganizationInvitationResponse.ValidateAll() if the designated
// constraints aren't met.
type ListOrganizationInvitationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListOrganizationInvitationResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListOrganizationInvitationResponseMultiError) AllErrors() []error { return m }

// ListOrganizationInvitationResponseValidationError is the validation error
// returned by ListOrganizationInvitationResponse.Validate if the designated
// constraints aren't met.
type ListOrganizationInvitationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListOrganizationInvitationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListOrganizationInvitationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListOrganizationInvitationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListOrganizationInvitationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListOrganizationInvitationResponseValidationError) ErrorName() string {
	return "ListOrganizationInvitationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListOrganizationInvitationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListOrganizationInvitationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListOrganizationInvitationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListOrganizationInvitationResponseValidationError{}

// Validate checks the field values on PutOrganizationInvitationRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *PutOrganizationInvitationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PutOrganizationInvitationRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// PutOrganizationInvitationRequestMultiError, or nil if none found.
func (m *PutOrganizationInvitationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PutOrganizationInvitationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOrganizationId() <= 0 {
		err := PutOrganizationInvitationRequestValidationError{
			field:  "OrganizationId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetProjectId() <= 0 {
		err := PutOrganizationInvitationRequestValidationError{
			field:  "ProjectId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _PutOrganizationInvitationRequest_Status_NotInLookup[m.GetStatus()]; ok {
		err := PutOrganizationInvitationRequestValidationError{
			field:  "Status",
			reason: "value must not be in list [0]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := OrganizationInvitationStatus_name[int32(m.GetStatus())]; !ok {
		err := PutOrganizationInvitationRequestValidationError{
			field:  "Status",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PutOrganizationInvitationRequestMultiError(errors)
	}

	return nil
}

// PutOrganizationInvitationRequestMultiError is an error wrapping multiple
// validation errors returned by
// PutOrganizationInvitationRequest.ValidateAll() if the designated
// constraints aren't met.
type PutOrganizationInvitationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PutOrganizationInvitationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PutOrganizationInvitationRequestMultiError) AllErrors() []error { return m }

// PutOrganizationInvitationRequestValidationError is the validation error
// returned by PutOrganizationInvitationRequest.Validate if the designated
// constraints aren't met.
type PutOrganizationInvitationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PutOrganizationInvitationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PutOrganizationInvitationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PutOrganizationInvitationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PutOrganizationInvitationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PutOrganizationInvitationRequestValidationError) ErrorName() string {
	return "PutOrganizationInvitationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PutOrganizationInvitationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPutOrganizationInvitationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PutOrganizationInvitationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PutOrganizationInvitationRequestValidationError{}

var _PutOrganizationInvitationRequest_Status_NotInLookup = map[OrganizationInvitationStatus]struct{}{
	0: {},
}

// Validate checks the field values on PutOrganizationInvitationResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *PutOrganizationInvitationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PutOrganizationInvitationResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// PutOrganizationInvitationResponseMultiError, or nil if none found.
func (m *PutOrganizationInvitationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PutOrganizationInvitationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOrganizationInvitation()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PutOrganizationInvitationResponseValidationError{
					field:  "OrganizationInvitation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PutOrganizationInvitationResponseValidationError{
					field:  "OrganizationInvitation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOrganizationInvitation()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PutOrganizationInvitationResponseValidationError{
				field:  "OrganizationInvitation",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PutOrganizationInvitationResponseMultiError(errors)
	}

	return nil
}

// PutOrganizationInvitationResponseMultiError is an error wrapping multiple
// validation errors returned by
// PutOrganizationInvitationResponse.ValidateAll() if the designated
// constraints aren't met.
type PutOrganizationInvitationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PutOrganizationInvitationResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PutOrganizationInvitationResponseMultiError) AllErrors() []error { return m }

// PutOrganizationInvitationResponseValidationError is the validation error
// returned by PutOrganizationInvitationResponse.Validate if the designated
// constraints aren't met.
type PutOrganizationInvitationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PutOrganizationInvitationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PutOrganizationInvitationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PutOrganizationInvitationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PutOrganizationInvitationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PutOrganizationInvitationResponseValidationError) ErrorName() string {
	return "PutOrganizationInvitationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PutOrganizationInvitationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPutOrganizationInvitationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PutOrganizationInvitationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PutOrganizationInvitationResponseValidationError{}

// Validate checks the field values on DeleteOrganizationInvitationRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *DeleteOrganizationInvitationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteOrganizationInvitationRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// DeleteOrganizationInvitationRequestMultiError, or nil if none found.
func (m *DeleteOrganizationInvitationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteOrganizationInvitationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOrganizationId() <= 0 {
		err := DeleteOrganizationInvitationRequestValidationError{
			field:  "OrganizationId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetProjectId() <= 0 {
		err := DeleteOrganizationInvitationRequestValidationError{
			field:  "ProjectId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteOrganizationInvitationRequestMultiError(errors)
	}

	return nil
}

// DeleteOrganizationInvitationRequestMultiError is an error wrapping multiple
// validation errors returned by
// DeleteOrganizationInvitationRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteOrganizationInvitationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteOrganizationInvitationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteOrganizationInvitationRequestMultiError) AllErrors() []error { return m }

// DeleteOrganizationInvitationRequestValidationError is the validation error
// returned by DeleteOrganizationInvitationRequest.Validate if the designated
// constraints aren't met.
type DeleteOrganizationInvitationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteOrganizationInvitationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteOrganizationInvitationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteOrganizationInvitationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteOrganizationInvitationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteOrganizationInvitationRequestValidationError) ErrorName() string {
	return "DeleteOrganizationInvitationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteOrganizationInvitationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteOrganizationInvitationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteOrganizationInvitationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteOrganizationInvitationRequestValidationError{}

// Validate checks the field values on ReplyOrganizationInvitationRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ReplyOrganizationInvitationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReplyOrganizationInvitationRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ReplyOrganizationInvitationRequestMultiError, or nil if none found.
func (m *ReplyOrganizationInvitationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReplyOrganizationInvitationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOrganizationId() <= 0 {
		err := ReplyOrganizationInvitationRequestValidationError{
			field:  "OrganizationId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetProjectId() <= 0 {
		err := ReplyOrganizationInvitationRequestValidationError{
			field:  "ProjectId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _ReplyOrganizationInvitationRequest_Status_NotInLookup[m.GetStatus()]; ok {
		err := ReplyOrganizationInvitationRequestValidationError{
			field:  "Status",
			reason: "value must not be in list [0]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := OrganizationInvitationStatus_name[int32(m.GetStatus())]; !ok {
		err := ReplyOrganizationInvitationRequestValidationError{
			field:  "Status",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ReplyOrganizationInvitationRequestMultiError(errors)
	}

	return nil
}

// ReplyOrganizationInvitationRequestMultiError is an error wrapping multiple
// validation errors returned by
// ReplyOrganizationInvitationRequest.ValidateAll() if the designated
// constraints aren't met.
type ReplyOrganizationInvitationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReplyOrganizationInvitationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReplyOrganizationInvitationRequestMultiError) AllErrors() []error { return m }

// ReplyOrganizationInvitationRequestValidationError is the validation error
// returned by ReplyOrganizationInvitationRequest.Validate if the designated
// constraints aren't met.
type ReplyOrganizationInvitationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReplyOrganizationInvitationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReplyOrganizationInvitationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReplyOrganizationInvitationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReplyOrganizationInvitationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReplyOrganizationInvitationRequestValidationError) ErrorName() string {
	return "ReplyOrganizationInvitationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ReplyOrganizationInvitationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReplyOrganizationInvitationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReplyOrganizationInvitationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReplyOrganizationInvitationRequestValidationError{}

var _ReplyOrganizationInvitationRequest_Status_NotInLookup = map[OrganizationInvitationStatus]struct{}{
	0: {},
}

// Validate checks the field values on ReplyOrganizationInvitationResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ReplyOrganizationInvitationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReplyOrganizationInvitationResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ReplyOrganizationInvitationResponseMultiError, or nil if none found.
func (m *ReplyOrganizationInvitationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReplyOrganizationInvitationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOrganizationProject()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReplyOrganizationInvitationResponseValidationError{
					field:  "OrganizationProject",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReplyOrganizationInvitationResponseValidationError{
					field:  "OrganizationProject",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOrganizationProject()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReplyOrganizationInvitationResponseValidationError{
				field:  "OrganizationProject",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ReplyOrganizationInvitationResponseMultiError(errors)
	}

	return nil
}

// ReplyOrganizationInvitationResponseMultiError is an error wrapping multiple
// validation errors returned by
// ReplyOrganizationInvitationResponse.ValidateAll() if the designated
// constraints aren't met.
type ReplyOrganizationInvitationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReplyOrganizationInvitationResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReplyOrganizationInvitationResponseMultiError) AllErrors() []error { return m }

// ReplyOrganizationInvitationResponseValidationError is the validation error
// returned by ReplyOrganizationInvitationResponse.Validate if the designated
// constraints aren't met.
type ReplyOrganizationInvitationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReplyOrganizationInvitationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReplyOrganizationInvitationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReplyOrganizationInvitationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReplyOrganizationInvitationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReplyOrganizationInvitationResponseValidationError) ErrorName() string {
	return "ReplyOrganizationInvitationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ReplyOrganizationInvitationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReplyOrganizationInvitationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReplyOrganizationInvitationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReplyOrganizationInvitationResponseValidationError{}
