// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: organization_iam/entity.proto

package organization_iam

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on OrganizationRole with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *OrganizationRole) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrganizationRole with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrganizationRoleMultiError, or nil if none found.
func (m *OrganizationRole) ValidateAll() error {
	return m.validate(true)
}

func (m *OrganizationRole) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RoleId

	// no validation rules for Name

	// no validation rules for OrganizationId

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return OrganizationRoleMultiError(errors)
	}

	return nil
}

// OrganizationRoleMultiError is an error wrapping multiple validation errors
// returned by OrganizationRole.ValidateAll() if the designated constraints
// aren't met.
type OrganizationRoleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrganizationRoleMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrganizationRoleMultiError) AllErrors() []error { return m }

// OrganizationRoleValidationError is the validation error returned by
// OrganizationRole.Validate if the designated constraints aren't met.
type OrganizationRoleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrganizationRoleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrganizationRoleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrganizationRoleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrganizationRoleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrganizationRoleValidationError) ErrorName() string { return "OrganizationRoleValidationError" }

// Error satisfies the builtin error interface
func (e OrganizationRoleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrganizationRole.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrganizationRoleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrganizationRoleValidationError{}

// Validate checks the field values on OrganizationPolicy with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OrganizationPolicy) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrganizationPolicy with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrganizationPolicyMultiError, or nil if none found.
func (m *OrganizationPolicy) ValidateAll() error {
	return m.validate(true)
}

func (m *OrganizationPolicy) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PolicyId

	// no validation rules for Name

	// no validation rules for OrganizationId

	// no validation rules for ActionPtn

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return OrganizationPolicyMultiError(errors)
	}

	return nil
}

// OrganizationPolicyMultiError is an error wrapping multiple validation errors
// returned by OrganizationPolicy.ValidateAll() if the designated constraints
// aren't met.
type OrganizationPolicyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrganizationPolicyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrganizationPolicyMultiError) AllErrors() []error { return m }

// OrganizationPolicyValidationError is the validation error returned by
// OrganizationPolicy.Validate if the designated constraints aren't met.
type OrganizationPolicyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrganizationPolicyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrganizationPolicyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrganizationPolicyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrganizationPolicyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrganizationPolicyValidationError) ErrorName() string {
	return "OrganizationPolicyValidationError"
}

// Error satisfies the builtin error interface
func (e OrganizationPolicyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrganizationPolicy.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrganizationPolicyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrganizationPolicyValidationError{}

// Validate checks the field values on OrganizationUserReserved with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OrganizationUserReserved) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrganizationUserReserved with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrganizationUserReservedMultiError, or nil if none found.
func (m *OrganizationUserReserved) ValidateAll() error {
	return m.validate(true)
}

func (m *OrganizationUserReserved) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReservedId

	// no validation rules for UserIdpKey

	// no validation rules for RoleId

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return OrganizationUserReservedMultiError(errors)
	}

	return nil
}

// OrganizationUserReservedMultiError is an error wrapping multiple validation
// errors returned by OrganizationUserReserved.ValidateAll() if the designated
// constraints aren't met.
type OrganizationUserReservedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrganizationUserReservedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrganizationUserReservedMultiError) AllErrors() []error { return m }

// OrganizationUserReservedValidationError is the validation error returned by
// OrganizationUserReserved.Validate if the designated constraints aren't met.
type OrganizationUserReservedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrganizationUserReservedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrganizationUserReservedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrganizationUserReservedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrganizationUserReservedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrganizationUserReservedValidationError) ErrorName() string {
	return "OrganizationUserReservedValidationError"
}

// Error satisfies the builtin error interface
func (e OrganizationUserReservedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrganizationUserReserved.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrganizationUserReservedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrganizationUserReservedValidationError{}

// Validate checks the field values on OrganizationAccessToken with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OrganizationAccessToken) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrganizationAccessToken with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrganizationAccessTokenMultiError, or nil if none found.
func (m *OrganizationAccessToken) ValidateAll() error {
	return m.validate(true)
}

func (m *OrganizationAccessToken) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccessTokenId

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for OrganizationId

	// no validation rules for ExpiredAt

	// no validation rules for LastUpdatedUserId

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return OrganizationAccessTokenMultiError(errors)
	}

	return nil
}

// OrganizationAccessTokenMultiError is an error wrapping multiple validation
// errors returned by OrganizationAccessToken.ValidateAll() if the designated
// constraints aren't met.
type OrganizationAccessTokenMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrganizationAccessTokenMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrganizationAccessTokenMultiError) AllErrors() []error { return m }

// OrganizationAccessTokenValidationError is the validation error returned by
// OrganizationAccessToken.Validate if the designated constraints aren't met.
type OrganizationAccessTokenValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrganizationAccessTokenValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrganizationAccessTokenValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrganizationAccessTokenValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrganizationAccessTokenValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrganizationAccessTokenValidationError) ErrorName() string {
	return "OrganizationAccessTokenValidationError"
}

// Error satisfies the builtin error interface
func (e OrganizationAccessTokenValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrganizationAccessToken.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrganizationAccessTokenValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrganizationAccessTokenValidationError{}
