// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	mock "github.com/stretchr/testify/mock"

	organization_alert "github.com/ca-risken/core/proto/organization_alert"
)

// OrganizationAlertServiceClient is an autogenerated mock type for the OrganizationAlertServiceClient type
type OrganizationAlertServiceClient struct {
	mock.Mock
}

// DeleteOrganizationNotification provides a mock function with given fields: ctx, in, opts
func (_m *OrganizationAlertServiceClient) DeleteOrganizationNotification(ctx context.Context, in *organization_alert.DeleteOrganizationNotificationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganizationNotification")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *organization_alert.DeleteOrganizationNotificationRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *organization_alert.DeleteOrganizationNotificationRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *organization_alert.DeleteOrganizationNotificationRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationNotification provides a mock function with given fields: ctx, in, opts
func (_m *OrganizationAlertServiceClient) GetOrganizationNotification(ctx context.Context, in *organization_alert.GetOrganizationNotificationRequest, opts ...grpc.CallOption) (*organization_alert.GetOrganizationNotificationResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationNotification")
	}

	var r0 *organization_alert.GetOrganizationNotificationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *organization_alert.GetOrganizationNotificationRequest, ...grpc.CallOption) (*organization_alert.GetOrganizationNotificationResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *organization_alert.GetOrganizationNotificationRequest, ...grpc.CallOption) *organization_alert.GetOrganizationNotificationResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*organization_alert.GetOrganizationNotificationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *organization_alert.GetOrganizationNotificationRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOrganizationNotification provides a mock function with given fields: ctx, in, opts
func (_m *OrganizationAlertServiceClient) ListOrganizationNotification(ctx context.Context, in *organization_alert.ListOrganizationNotificationRequest, opts ...grpc.CallOption) (*organization_alert.ListOrganizationNotificationResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListOrganizationNotification")
	}

	var r0 *organization_alert.ListOrganizationNotificationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *organization_alert.ListOrganizationNotificationRequest, ...grpc.CallOption) (*organization_alert.ListOrganizationNotificationResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *organization_alert.ListOrganizationNotificationRequest, ...grpc.CallOption) *organization_alert.ListOrganizationNotificationResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*organization_alert.ListOrganizationNotificationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *organization_alert.ListOrganizationNotificationRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOrganizationNotificationByProject provides a mock function with given fields: ctx, in, opts
func (_m *OrganizationAlertServiceClient) ListOrganizationNotificationByProject(ctx context.Context, in *organization_alert.ListOrganizationNotificationByProjectRequest, opts ...grpc.CallOption) (*organization_alert.ListOrganizationNotificationByProjectResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListOrganizationNotificationByProject")
	}

	var r0 *organization_alert.ListOrganizationNotificationByProjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *organization_alert.ListOrganizationNotificationByProjectRequest, ...grpc.CallOption) (*organization_alert.ListOrganizationNotificationByProjectResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *organization_alert.ListOrganizationNotificationByProjectRequest, ...grpc.CallOption) *organization_alert.ListOrganizationNotificationByProjectResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*organization_alert.ListOrganizationNotificationByProjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *organization_alert.ListOrganizationNotificationByProjectRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutOrganizationNotification provides a mock function with given fields: ctx, in, opts
func (_m *OrganizationAlertServiceClient) PutOrganizationNotification(ctx context.Context, in *organization_alert.PutOrganizationNotificationRequest, opts ...grpc.CallOption) (*organization_alert.PutOrganizationNotificationResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutOrganizationNotification")
	}

	var r0 *organization_alert.PutOrganizationNotificationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *organization_alert.PutOrganizationNotificationRequest, ...grpc.CallOption) (*organization_alert.PutOrganizationNotificationResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *organization_alert.PutOrganizationNotificationRequest, ...grpc.CallOption) *organization_alert.PutOrganizationNotificationResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*organization_alert.PutOrganizationNotificationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *organization_alert.PutOrganizationNotificationRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TestOrganizationNotification provides a mock function with given fields: ctx, in, opts
func (_m *OrganizationAlertServiceClient) TestOrganizationNotification(ctx context.Context, in *organization_alert.TestOrganizationNotificationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for TestOrganizationNotification")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *organization_alert.TestOrganizationNotificationRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *organization_alert.TestOrganizationNotificationRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *organization_alert.TestOrganizationNotificationRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrganizationAlertServiceClient creates a new instance of OrganizationAlertServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationAlertServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationAlertServiceClient {
	mock := &OrganizationAlertServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
