// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: org_iam/role.proto

package org_iam

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListOrgRoleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListOrgRoleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListOrgRoleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListOrgRoleRequestMultiError, or nil if none found.
func (m *ListOrgRoleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListOrgRoleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrganizationId

	if utf8.RuneCountInString(m.GetName()) > 64 {
		err := ListOrgRoleRequestValidationError{
			field:  "Name",
			reason: "value length must be at most 64 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for UserId

	// no validation rules for AccessTokenId

	if len(errors) > 0 {
		return ListOrgRoleRequestMultiError(errors)
	}

	return nil
}

// ListOrgRoleRequestMultiError is an error wrapping multiple validation errors
// returned by ListOrgRoleRequest.ValidateAll() if the designated constraints
// aren't met.
type ListOrgRoleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListOrgRoleRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListOrgRoleRequestMultiError) AllErrors() []error { return m }

// ListOrgRoleRequestValidationError is the validation error returned by
// ListOrgRoleRequest.Validate if the designated constraints aren't met.
type ListOrgRoleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListOrgRoleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListOrgRoleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListOrgRoleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListOrgRoleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListOrgRoleRequestValidationError) ErrorName() string {
	return "ListOrgRoleRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListOrgRoleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListOrgRoleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListOrgRoleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListOrgRoleRequestValidationError{}

// Validate checks the field values on ListOrgRoleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListOrgRoleResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListOrgRoleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListOrgRoleResponseMultiError, or nil if none found.
func (m *ListOrgRoleResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListOrgRoleResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListOrgRoleResponseMultiError(errors)
	}

	return nil
}

// ListOrgRoleResponseMultiError is an error wrapping multiple validation
// errors returned by ListOrgRoleResponse.ValidateAll() if the designated
// constraints aren't met.
type ListOrgRoleResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListOrgRoleResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListOrgRoleResponseMultiError) AllErrors() []error { return m }

// ListOrgRoleResponseValidationError is the validation error returned by
// ListOrgRoleResponse.Validate if the designated constraints aren't met.
type ListOrgRoleResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListOrgRoleResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListOrgRoleResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListOrgRoleResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListOrgRoleResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListOrgRoleResponseValidationError) ErrorName() string {
	return "ListOrgRoleResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListOrgRoleResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListOrgRoleResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListOrgRoleResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListOrgRoleResponseValidationError{}

// Validate checks the field values on GetOrgRoleRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetOrgRoleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetOrgRoleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetOrgRoleRequestMultiError, or nil if none found.
func (m *GetOrgRoleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetOrgRoleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOrganizationId() <= 0 {
		err := GetOrgRoleRequestValidationError{
			field:  "OrganizationId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetRoleId() <= 0 {
		err := GetOrgRoleRequestValidationError{
			field:  "RoleId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetOrgRoleRequestMultiError(errors)
	}

	return nil
}

// GetOrgRoleRequestMultiError is an error wrapping multiple validation errors
// returned by GetOrgRoleRequest.ValidateAll() if the designated constraints
// aren't met.
type GetOrgRoleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetOrgRoleRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetOrgRoleRequestMultiError) AllErrors() []error { return m }

// GetOrgRoleRequestValidationError is the validation error returned by
// GetOrgRoleRequest.Validate if the designated constraints aren't met.
type GetOrgRoleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetOrgRoleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetOrgRoleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetOrgRoleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetOrgRoleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetOrgRoleRequestValidationError) ErrorName() string {
	return "GetOrgRoleRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetOrgRoleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetOrgRoleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetOrgRoleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetOrgRoleRequestValidationError{}

// Validate checks the field values on GetOrgRoleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetOrgRoleResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetOrgRoleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetOrgRoleResponseMultiError, or nil if none found.
func (m *GetOrgRoleResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetOrgRoleResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRole()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetOrgRoleResponseValidationError{
					field:  "Role",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetOrgRoleResponseValidationError{
					field:  "Role",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRole()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetOrgRoleResponseValidationError{
				field:  "Role",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetOrgRoleResponseMultiError(errors)
	}

	return nil
}

// GetOrgRoleResponseMultiError is an error wrapping multiple validation errors
// returned by GetOrgRoleResponse.ValidateAll() if the designated constraints
// aren't met.
type GetOrgRoleResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetOrgRoleResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetOrgRoleResponseMultiError) AllErrors() []error { return m }

// GetOrgRoleResponseValidationError is the validation error returned by
// GetOrgRoleResponse.Validate if the designated constraints aren't met.
type GetOrgRoleResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetOrgRoleResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetOrgRoleResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetOrgRoleResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetOrgRoleResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetOrgRoleResponseValidationError) ErrorName() string {
	return "GetOrgRoleResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetOrgRoleResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetOrgRoleResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetOrgRoleResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetOrgRoleResponseValidationError{}

// Validate checks the field values on PutOrgRoleRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PutOrgRoleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PutOrgRoleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PutOrgRoleRequestMultiError, or nil if none found.
func (m *PutOrgRoleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PutOrgRoleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOrganizationId() <= 0 {
		err := PutOrgRoleRequestValidationError{
			field:  "OrganizationId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 64 {
		err := PutOrgRoleRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PutOrgRoleRequestMultiError(errors)
	}

	return nil
}

// PutOrgRoleRequestMultiError is an error wrapping multiple validation errors
// returned by PutOrgRoleRequest.ValidateAll() if the designated constraints
// aren't met.
type PutOrgRoleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PutOrgRoleRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PutOrgRoleRequestMultiError) AllErrors() []error { return m }

// PutOrgRoleRequestValidationError is the validation error returned by
// PutOrgRoleRequest.Validate if the designated constraints aren't met.
type PutOrgRoleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PutOrgRoleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PutOrgRoleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PutOrgRoleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PutOrgRoleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PutOrgRoleRequestValidationError) ErrorName() string {
	return "PutOrgRoleRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PutOrgRoleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPutOrgRoleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PutOrgRoleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PutOrgRoleRequestValidationError{}

// Validate checks the field values on PutOrgRoleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PutOrgRoleResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PutOrgRoleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PutOrgRoleResponseMultiError, or nil if none found.
func (m *PutOrgRoleResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PutOrgRoleResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRole()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PutOrgRoleResponseValidationError{
					field:  "Role",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PutOrgRoleResponseValidationError{
					field:  "Role",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRole()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PutOrgRoleResponseValidationError{
				field:  "Role",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PutOrgRoleResponseMultiError(errors)
	}

	return nil
}

// PutOrgRoleResponseMultiError is an error wrapping multiple validation errors
// returned by PutOrgRoleResponse.ValidateAll() if the designated constraints
// aren't met.
type PutOrgRoleResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PutOrgRoleResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PutOrgRoleResponseMultiError) AllErrors() []error { return m }

// PutOrgRoleResponseValidationError is the validation error returned by
// PutOrgRoleResponse.Validate if the designated constraints aren't met.
type PutOrgRoleResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PutOrgRoleResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PutOrgRoleResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PutOrgRoleResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PutOrgRoleResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PutOrgRoleResponseValidationError) ErrorName() string {
	return "PutOrgRoleResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PutOrgRoleResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPutOrgRoleResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PutOrgRoleResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PutOrgRoleResponseValidationError{}

// Validate checks the field values on DeleteOrgRoleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteOrgRoleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteOrgRoleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteOrgRoleRequestMultiError, or nil if none found.
func (m *DeleteOrgRoleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteOrgRoleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetOrganizationId() <= 0 {
		err := DeleteOrgRoleRequestValidationError{
			field:  "OrganizationId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetRoleId() <= 0 {
		err := DeleteOrgRoleRequestValidationError{
			field:  "RoleId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteOrgRoleRequestMultiError(errors)
	}

	return nil
}

// DeleteOrgRoleRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteOrgRoleRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteOrgRoleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteOrgRoleRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteOrgRoleRequestMultiError) AllErrors() []error { return m }

// DeleteOrgRoleRequestValidationError is the validation error returned by
// DeleteOrgRoleRequest.Validate if the designated constraints aren't met.
type DeleteOrgRoleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteOrgRoleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteOrgRoleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteOrgRoleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteOrgRoleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteOrgRoleRequestValidationError) ErrorName() string {
	return "DeleteOrgRoleRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteOrgRoleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteOrgRoleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteOrgRoleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteOrgRoleRequestValidationError{}

// Validate checks the field values on AttachOrgRoleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AttachOrgRoleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AttachOrgRoleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AttachOrgRoleRequestMultiError, or nil if none found.
func (m *AttachOrgRoleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AttachOrgRoleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := AttachOrgRoleRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetRoleId() <= 0 {
		err := AttachOrgRoleRequestValidationError{
			field:  "RoleId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOrganizationId() <= 0 {
		err := AttachOrgRoleRequestValidationError{
			field:  "OrganizationId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AttachOrgRoleRequestMultiError(errors)
	}

	return nil
}

// AttachOrgRoleRequestMultiError is an error wrapping multiple validation
// errors returned by AttachOrgRoleRequest.ValidateAll() if the designated
// constraints aren't met.
type AttachOrgRoleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AttachOrgRoleRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AttachOrgRoleRequestMultiError) AllErrors() []error { return m }

// AttachOrgRoleRequestValidationError is the validation error returned by
// AttachOrgRoleRequest.Validate if the designated constraints aren't met.
type AttachOrgRoleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AttachOrgRoleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AttachOrgRoleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AttachOrgRoleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AttachOrgRoleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AttachOrgRoleRequestValidationError) ErrorName() string {
	return "AttachOrgRoleRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AttachOrgRoleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAttachOrgRoleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AttachOrgRoleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AttachOrgRoleRequestValidationError{}

// Validate checks the field values on AttachOrgRoleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AttachOrgRoleResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AttachOrgRoleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AttachOrgRoleResponseMultiError, or nil if none found.
func (m *AttachOrgRoleResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AttachOrgRoleResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRole()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AttachOrgRoleResponseValidationError{
					field:  "Role",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AttachOrgRoleResponseValidationError{
					field:  "Role",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRole()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AttachOrgRoleResponseValidationError{
				field:  "Role",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AttachOrgRoleResponseMultiError(errors)
	}

	return nil
}

// AttachOrgRoleResponseMultiError is an error wrapping multiple validation
// errors returned by AttachOrgRoleResponse.ValidateAll() if the designated
// constraints aren't met.
type AttachOrgRoleResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AttachOrgRoleResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AttachOrgRoleResponseMultiError) AllErrors() []error { return m }

// AttachOrgRoleResponseValidationError is the validation error returned by
// AttachOrgRoleResponse.Validate if the designated constraints aren't met.
type AttachOrgRoleResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AttachOrgRoleResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AttachOrgRoleResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AttachOrgRoleResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AttachOrgRoleResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AttachOrgRoleResponseValidationError) ErrorName() string {
	return "AttachOrgRoleResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AttachOrgRoleResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAttachOrgRoleResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AttachOrgRoleResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AttachOrgRoleResponseValidationError{}

// Validate checks the field values on DetachOrgRoleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DetachOrgRoleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DetachOrgRoleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DetachOrgRoleRequestMultiError, or nil if none found.
func (m *DetachOrgRoleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DetachOrgRoleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := DetachOrgRoleRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetRoleId() <= 0 {
		err := DetachOrgRoleRequestValidationError{
			field:  "RoleId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOrganizationId() <= 0 {
		err := DetachOrgRoleRequestValidationError{
			field:  "OrganizationId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DetachOrgRoleRequestMultiError(errors)
	}

	return nil
}

// DetachOrgRoleRequestMultiError is an error wrapping multiple validation
// errors returned by DetachOrgRoleRequest.ValidateAll() if the designated
// constraints aren't met.
type DetachOrgRoleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DetachOrgRoleRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DetachOrgRoleRequestMultiError) AllErrors() []error { return m }

// DetachOrgRoleRequestValidationError is the validation error returned by
// DetachOrgRoleRequest.Validate if the designated constraints aren't met.
type DetachOrgRoleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DetachOrgRoleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DetachOrgRoleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DetachOrgRoleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DetachOrgRoleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DetachOrgRoleRequestValidationError) ErrorName() string {
	return "DetachOrgRoleRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DetachOrgRoleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDetachOrgRoleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DetachOrgRoleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DetachOrgRoleRequestValidationError{}

// Validate checks the field values on AttachOrgRoleByOrgUserReservedRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *AttachOrgRoleByOrgUserReservedRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AttachOrgRoleByOrgUserReservedRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// AttachOrgRoleByOrgUserReservedRequestMultiError, or nil if none found.
func (m *AttachOrgRoleByOrgUserReservedRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AttachOrgRoleByOrgUserReservedRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := AttachOrgRoleByOrgUserReservedRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetUserIdpKey()) > 255 {
		err := AttachOrgRoleByOrgUserReservedRequestValidationError{
			field:  "UserIdpKey",
			reason: "value length must be at most 255 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AttachOrgRoleByOrgUserReservedRequestMultiError(errors)
	}

	return nil
}

// AttachOrgRoleByOrgUserReservedRequestMultiError is an error wrapping
// multiple validation errors returned by
// AttachOrgRoleByOrgUserReservedRequest.ValidateAll() if the designated
// constraints aren't met.
type AttachOrgRoleByOrgUserReservedRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AttachOrgRoleByOrgUserReservedRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AttachOrgRoleByOrgUserReservedRequestMultiError) AllErrors() []error { return m }

// AttachOrgRoleByOrgUserReservedRequestValidationError is the validation error
// returned by AttachOrgRoleByOrgUserReservedRequest.Validate if the
// designated constraints aren't met.
type AttachOrgRoleByOrgUserReservedRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AttachOrgRoleByOrgUserReservedRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AttachOrgRoleByOrgUserReservedRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AttachOrgRoleByOrgUserReservedRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AttachOrgRoleByOrgUserReservedRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AttachOrgRoleByOrgUserReservedRequestValidationError) ErrorName() string {
	return "AttachOrgRoleByOrgUserReservedRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AttachOrgRoleByOrgUserReservedRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAttachOrgRoleByOrgUserReservedRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AttachOrgRoleByOrgUserReservedRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AttachOrgRoleByOrgUserReservedRequestValidationError{}

// Validate checks the field values on AttachOrgRoleByOrgUserReservedResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *AttachOrgRoleByOrgUserReservedResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// AttachOrgRoleByOrgUserReservedResponse with the rules defined in the proto
// definition for this message. If any rules are violated, the result is a
// list of violation errors wrapped in
// AttachOrgRoleByOrgUserReservedResponseMultiError, or nil if none found.
func (m *AttachOrgRoleByOrgUserReservedResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AttachOrgRoleByOrgUserReservedResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRole()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AttachOrgRoleByOrgUserReservedResponseValidationError{
					field:  "Role",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AttachOrgRoleByOrgUserReservedResponseValidationError{
					field:  "Role",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRole()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AttachOrgRoleByOrgUserReservedResponseValidationError{
				field:  "Role",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AttachOrgRoleByOrgUserReservedResponseMultiError(errors)
	}

	return nil
}

// AttachOrgRoleByOrgUserReservedResponseMultiError is an error wrapping
// multiple validation errors returned by
// AttachOrgRoleByOrgUserReservedResponse.ValidateAll() if the designated
// constraints aren't met.
type AttachOrgRoleByOrgUserReservedResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AttachOrgRoleByOrgUserReservedResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AttachOrgRoleByOrgUserReservedResponseMultiError) AllErrors() []error { return m }

// AttachOrgRoleByOrgUserReservedResponseValidationError is the validation
// error returned by AttachOrgRoleByOrgUserReservedResponse.Validate if the
// designated constraints aren't met.
type AttachOrgRoleByOrgUserReservedResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AttachOrgRoleByOrgUserReservedResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AttachOrgRoleByOrgUserReservedResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AttachOrgRoleByOrgUserReservedResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AttachOrgRoleByOrgUserReservedResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AttachOrgRoleByOrgUserReservedResponseValidationError) ErrorName() string {
	return "AttachOrgRoleByOrgUserReservedResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AttachOrgRoleByOrgUserReservedResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAttachOrgRoleByOrgUserReservedResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AttachOrgRoleByOrgUserReservedResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AttachOrgRoleByOrgUserReservedResponseValidationError{}
