batch:
  build-graph:
    - identifier: build_arm64
      buildspec: codebuild/test-go-upgrade/buildspec-image.yml
      env:
        compute-type: BUILD_GENERAL1_LARGE
        image: aws/codebuild/amazonlinux2-aarch64-standard:2.0
        privileged-mode: true
        type: ARM_CONTAINER
        variables:
          OS: linux
          ARCH: arm64


