// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: organization_alert/service.proto

package organization_alert

import (
	context "context"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListOrganizationNotification
type ListOrganizationNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationId uint32 `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
}

func (x *ListOrganizationNotificationRequest) Reset() {
	*x = ListOrganizationNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_alert_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOrganizationNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationNotificationRequest) ProtoMessage() {}

func (x *ListOrganizationNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_alert_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationNotificationRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationNotificationRequest) Descriptor() ([]byte, []int) {
	return file_organization_alert_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListOrganizationNotificationRequest) GetOrganizationId() uint32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

type ListOrganizationNotificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationNotification []*OrganizationNotification `protobuf:"bytes,1,rep,name=organization_notification,json=organizationNotification,proto3" json:"organization_notification,omitempty"`
}

func (x *ListOrganizationNotificationResponse) Reset() {
	*x = ListOrganizationNotificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_alert_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOrganizationNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationNotificationResponse) ProtoMessage() {}

func (x *ListOrganizationNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_alert_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationNotificationResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationNotificationResponse) Descriptor() ([]byte, []int) {
	return file_organization_alert_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListOrganizationNotificationResponse) GetOrganizationNotification() []*OrganizationNotification {
	if x != nil {
		return x.OrganizationNotification
	}
	return nil
}

// GetOrganizationNotification
type GetOrganizationNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationId uint32 `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	NotificationId uint32 `protobuf:"varint,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
}

func (x *GetOrganizationNotificationRequest) Reset() {
	*x = GetOrganizationNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_alert_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrganizationNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationNotificationRequest) ProtoMessage() {}

func (x *GetOrganizationNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_alert_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationNotificationRequest) Descriptor() ([]byte, []int) {
	return file_organization_alert_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrganizationNotificationRequest) GetOrganizationId() uint32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *GetOrganizationNotificationRequest) GetNotificationId() uint32 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

type GetOrganizationNotificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationNotification *OrganizationNotification `protobuf:"bytes,1,opt,name=organization_notification,json=organizationNotification,proto3" json:"organization_notification,omitempty"`
}

func (x *GetOrganizationNotificationResponse) Reset() {
	*x = GetOrganizationNotificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_alert_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrganizationNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationNotificationResponse) ProtoMessage() {}

func (x *GetOrganizationNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_alert_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationNotificationResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizationNotificationResponse) Descriptor() ([]byte, []int) {
	return file_organization_alert_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrganizationNotificationResponse) GetOrganizationNotification() *OrganizationNotification {
	if x != nil {
		return x.OrganizationNotification
	}
	return nil
}

// PutOrganizationNotification
type PutOrganizationNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationId uint32 `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	NotificationId uint32 `protobuf:"varint,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Name           string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type           string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	NotifySetting  string `protobuf:"bytes,5,opt,name=notify_setting,json=notifySetting,proto3" json:"notify_setting,omitempty"`
}

func (x *PutOrganizationNotificationRequest) Reset() {
	*x = PutOrganizationNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_alert_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutOrganizationNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutOrganizationNotificationRequest) ProtoMessage() {}

func (x *PutOrganizationNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_alert_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutOrganizationNotificationRequest.ProtoReflect.Descriptor instead.
func (*PutOrganizationNotificationRequest) Descriptor() ([]byte, []int) {
	return file_organization_alert_service_proto_rawDescGZIP(), []int{4}
}

func (x *PutOrganizationNotificationRequest) GetOrganizationId() uint32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *PutOrganizationNotificationRequest) GetNotificationId() uint32 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

func (x *PutOrganizationNotificationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutOrganizationNotificationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PutOrganizationNotificationRequest) GetNotifySetting() string {
	if x != nil {
		return x.NotifySetting
	}
	return ""
}

type PutOrganizationNotificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationNotification *OrganizationNotification `protobuf:"bytes,1,opt,name=organization_notification,json=organizationNotification,proto3" json:"organization_notification,omitempty"`
}

func (x *PutOrganizationNotificationResponse) Reset() {
	*x = PutOrganizationNotificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_alert_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutOrganizationNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutOrganizationNotificationResponse) ProtoMessage() {}

func (x *PutOrganizationNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_alert_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutOrganizationNotificationResponse.ProtoReflect.Descriptor instead.
func (*PutOrganizationNotificationResponse) Descriptor() ([]byte, []int) {
	return file_organization_alert_service_proto_rawDescGZIP(), []int{5}
}

func (x *PutOrganizationNotificationResponse) GetOrganizationNotification() *OrganizationNotification {
	if x != nil {
		return x.OrganizationNotification
	}
	return nil
}

// DeleteOrganizationNotification
type DeleteOrganizationNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationId uint32 `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	NotificationId uint32 `protobuf:"varint,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
}

func (x *DeleteOrganizationNotificationRequest) Reset() {
	*x = DeleteOrganizationNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_alert_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteOrganizationNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationNotificationRequest) ProtoMessage() {}

func (x *DeleteOrganizationNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_alert_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationNotificationRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationNotificationRequest) Descriptor() ([]byte, []int) {
	return file_organization_alert_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteOrganizationNotificationRequest) GetOrganizationId() uint32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *DeleteOrganizationNotificationRequest) GetNotificationId() uint32 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

// TestOrganizationNotification
type TestOrganizationNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationId uint32 `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	NotificationId uint32 `protobuf:"varint,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
}

func (x *TestOrganizationNotificationRequest) Reset() {
	*x = TestOrganizationNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_alert_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestOrganizationNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestOrganizationNotificationRequest) ProtoMessage() {}

func (x *TestOrganizationNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_alert_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestOrganizationNotificationRequest.ProtoReflect.Descriptor instead.
func (*TestOrganizationNotificationRequest) Descriptor() ([]byte, []int) {
	return file_organization_alert_service_proto_rawDescGZIP(), []int{7}
}

func (x *TestOrganizationNotificationRequest) GetOrganizationId() uint32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *TestOrganizationNotificationRequest) GetNotificationId() uint32 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

var File_organization_alert_service_proto protoreflect.FileDescriptor

var file_organization_alert_service_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61,
	0x6c, 0x65, 0x72, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x17, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2f, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x57, 0x0a, 0x23, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x0f, 0x6f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x0e, 0x6f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x96, 0x01, 0x0a, 0x24,
	0x4c, 0x69, 0x73, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6e, 0x0a, 0x19, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6c, 0x65, 0x72,
	0x74, 0x2e, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x18, 0x6f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x88, 0x01, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x0f, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x0e, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x30, 0x0a,
	0x0f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52,
	0x0e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22,
	0x95, 0x01, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6e, 0x0a, 0x19, 0x6f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61,
	0x6c, 0x65, 0x72, 0x74, 0x2e, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x18, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xee, 0x01, 0x0a, 0x22, 0x50, 0x75, 0x74, 0x4f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30,
	0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00,
	0x52, 0x0e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x27, 0x0a, 0x0f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x72, 0x05, 0x10, 0x01,
	0x18, 0xc8, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x72, 0x04, 0x10, 0x01,
	0x18, 0x40, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x0e, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x95, 0x01, 0x0a, 0x23, 0x50, 0x75, 0x74,
	0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x6e, 0x0a, 0x19, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x4f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x18, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x8b, 0x01, 0x0a, 0x25, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x0f, 0x6f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x0e, 0x6f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x0f,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x0e,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x89,
	0x01, 0x0a, 0x23, 0x54, 0x65, 0x73, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x0e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x0f, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x0e, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x32, 0xe8, 0x05, 0x0a, 0x18, 0x4f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x65, 0x72, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x9d, 0x01, 0x0a, 0x1c, 0x4c, 0x69, 0x73, 0x74,
	0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6c, 0x65,
	0x72, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3d, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x9a, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6c, 0x65, 0x72,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x3c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x9a, 0x01, 0x0a, 0x1b, 0x50, 0x75, 0x74, 0x4f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x50,
	0x75, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x3c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x50, 0x75, 0x74, 0x4f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x7a, 0x0a, 0x1e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x3e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x76, 0x0a,
	0x1c, 0x54, 0x65, 0x73, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x4f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x2d, 0x72, 0x69, 0x73, 0x6b, 0x65, 0x6e, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_organization_alert_service_proto_rawDescOnce sync.Once
	file_organization_alert_service_proto_rawDescData = file_organization_alert_service_proto_rawDesc
)

func file_organization_alert_service_proto_rawDescGZIP() []byte {
	file_organization_alert_service_proto_rawDescOnce.Do(func() {
		file_organization_alert_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_organization_alert_service_proto_rawDescData)
	})
	return file_organization_alert_service_proto_rawDescData
}

var file_organization_alert_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_organization_alert_service_proto_goTypes = []interface{}{
	(*ListOrganizationNotificationRequest)(nil),   // 0: core.organization_alert.ListOrganizationNotificationRequest
	(*ListOrganizationNotificationResponse)(nil),  // 1: core.organization_alert.ListOrganizationNotificationResponse
	(*GetOrganizationNotificationRequest)(nil),    // 2: core.organization_alert.GetOrganizationNotificationRequest
	(*GetOrganizationNotificationResponse)(nil),   // 3: core.organization_alert.GetOrganizationNotificationResponse
	(*PutOrganizationNotificationRequest)(nil),    // 4: core.organization_alert.PutOrganizationNotificationRequest
	(*PutOrganizationNotificationResponse)(nil),   // 5: core.organization_alert.PutOrganizationNotificationResponse
	(*DeleteOrganizationNotificationRequest)(nil), // 6: core.organization_alert.DeleteOrganizationNotificationRequest
	(*TestOrganizationNotificationRequest)(nil),   // 7: core.organization_alert.TestOrganizationNotificationRequest
	(*OrganizationNotification)(nil),              // 8: core.organization_alert.OrganizationNotification
	(*emptypb.Empty)(nil),                         // 9: google.protobuf.Empty
}
var file_organization_alert_service_proto_depIdxs = []int32{
	8, // 0: core.organization_alert.ListOrganizationNotificationResponse.organization_notification:type_name -> core.organization_alert.OrganizationNotification
	8, // 1: core.organization_alert.GetOrganizationNotificationResponse.organization_notification:type_name -> core.organization_alert.OrganizationNotification
	8, // 2: core.organization_alert.PutOrganizationNotificationResponse.organization_notification:type_name -> core.organization_alert.OrganizationNotification
	0, // 3: core.organization_alert.OrganizationAlertService.ListOrganizationNotification:input_type -> core.organization_alert.ListOrganizationNotificationRequest
	2, // 4: core.organization_alert.OrganizationAlertService.GetOrganizationNotification:input_type -> core.organization_alert.GetOrganizationNotificationRequest
	4, // 5: core.organization_alert.OrganizationAlertService.PutOrganizationNotification:input_type -> core.organization_alert.PutOrganizationNotificationRequest
	6, // 6: core.organization_alert.OrganizationAlertService.DeleteOrganizationNotification:input_type -> core.organization_alert.DeleteOrganizationNotificationRequest
	7, // 7: core.organization_alert.OrganizationAlertService.TestOrganizationNotification:input_type -> core.organization_alert.TestOrganizationNotificationRequest
	1, // 8: core.organization_alert.OrganizationAlertService.ListOrganizationNotification:output_type -> core.organization_alert.ListOrganizationNotificationResponse
	3, // 9: core.organization_alert.OrganizationAlertService.GetOrganizationNotification:output_type -> core.organization_alert.GetOrganizationNotificationResponse
	5, // 10: core.organization_alert.OrganizationAlertService.PutOrganizationNotification:output_type -> core.organization_alert.PutOrganizationNotificationResponse
	9, // 11: core.organization_alert.OrganizationAlertService.DeleteOrganizationNotification:output_type -> google.protobuf.Empty
	9, // 12: core.organization_alert.OrganizationAlertService.TestOrganizationNotification:output_type -> google.protobuf.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_organization_alert_service_proto_init() }
func file_organization_alert_service_proto_init() {
	if File_organization_alert_service_proto != nil {
		return
	}
	file_organization_alert_entity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_organization_alert_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOrganizationNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_organization_alert_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOrganizationNotificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_organization_alert_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrganizationNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_organization_alert_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrganizationNotificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_organization_alert_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutOrganizationNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_organization_alert_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutOrganizationNotificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_organization_alert_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteOrganizationNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_organization_alert_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestOrganizationNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_organization_alert_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_organization_alert_service_proto_goTypes,
		DependencyIndexes: file_organization_alert_service_proto_depIdxs,
		MessageInfos:      file_organization_alert_service_proto_msgTypes,
	}.Build()
	File_organization_alert_service_proto = out.File
	file_organization_alert_service_proto_rawDesc = nil
	file_organization_alert_service_proto_goTypes = nil
	file_organization_alert_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrganizationAlertServiceClient is the client API for OrganizationAlertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrganizationAlertServiceClient interface {
	ListOrganizationNotification(ctx context.Context, in *ListOrganizationNotificationRequest, opts ...grpc.CallOption) (*ListOrganizationNotificationResponse, error)
	GetOrganizationNotification(ctx context.Context, in *GetOrganizationNotificationRequest, opts ...grpc.CallOption) (*GetOrganizationNotificationResponse, error)
	PutOrganizationNotification(ctx context.Context, in *PutOrganizationNotificationRequest, opts ...grpc.CallOption) (*PutOrganizationNotificationResponse, error)
	DeleteOrganizationNotification(ctx context.Context, in *DeleteOrganizationNotificationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	TestOrganizationNotification(ctx context.Context, in *TestOrganizationNotificationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type organizationAlertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrganizationAlertServiceClient(cc grpc.ClientConnInterface) OrganizationAlertServiceClient {
	return &organizationAlertServiceClient{cc}
}

func (c *organizationAlertServiceClient) ListOrganizationNotification(ctx context.Context, in *ListOrganizationNotificationRequest, opts ...grpc.CallOption) (*ListOrganizationNotificationResponse, error) {
	out := new(ListOrganizationNotificationResponse)
	err := c.cc.Invoke(ctx, "/core.organization_alert.OrganizationAlertService/ListOrganizationNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationAlertServiceClient) GetOrganizationNotification(ctx context.Context, in *GetOrganizationNotificationRequest, opts ...grpc.CallOption) (*GetOrganizationNotificationResponse, error) {
	out := new(GetOrganizationNotificationResponse)
	err := c.cc.Invoke(ctx, "/core.organization_alert.OrganizationAlertService/GetOrganizationNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationAlertServiceClient) PutOrganizationNotification(ctx context.Context, in *PutOrganizationNotificationRequest, opts ...grpc.CallOption) (*PutOrganizationNotificationResponse, error) {
	out := new(PutOrganizationNotificationResponse)
	err := c.cc.Invoke(ctx, "/core.organization_alert.OrganizationAlertService/PutOrganizationNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationAlertServiceClient) DeleteOrganizationNotification(ctx context.Context, in *DeleteOrganizationNotificationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/core.organization_alert.OrganizationAlertService/DeleteOrganizationNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationAlertServiceClient) TestOrganizationNotification(ctx context.Context, in *TestOrganizationNotificationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/core.organization_alert.OrganizationAlertService/TestOrganizationNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrganizationAlertServiceServer is the server API for OrganizationAlertService service.
type OrganizationAlertServiceServer interface {
	ListOrganizationNotification(context.Context, *ListOrganizationNotificationRequest) (*ListOrganizationNotificationResponse, error)
	GetOrganizationNotification(context.Context, *GetOrganizationNotificationRequest) (*GetOrganizationNotificationResponse, error)
	PutOrganizationNotification(context.Context, *PutOrganizationNotificationRequest) (*PutOrganizationNotificationResponse, error)
	DeleteOrganizationNotification(context.Context, *DeleteOrganizationNotificationRequest) (*emptypb.Empty, error)
	TestOrganizationNotification(context.Context, *TestOrganizationNotificationRequest) (*emptypb.Empty, error)
}

// UnimplementedOrganizationAlertServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrganizationAlertServiceServer struct {
}

func (*UnimplementedOrganizationAlertServiceServer) ListOrganizationNotification(context.Context, *ListOrganizationNotificationRequest) (*ListOrganizationNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrganizationNotification not implemented")
}
func (*UnimplementedOrganizationAlertServiceServer) GetOrganizationNotification(context.Context, *GetOrganizationNotificationRequest) (*GetOrganizationNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganizationNotification not implemented")
}
func (*UnimplementedOrganizationAlertServiceServer) PutOrganizationNotification(context.Context, *PutOrganizationNotificationRequest) (*PutOrganizationNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutOrganizationNotification not implemented")
}
func (*UnimplementedOrganizationAlertServiceServer) DeleteOrganizationNotification(context.Context, *DeleteOrganizationNotificationRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOrganizationNotification not implemented")
}
func (*UnimplementedOrganizationAlertServiceServer) TestOrganizationNotification(context.Context, *TestOrganizationNotificationRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestOrganizationNotification not implemented")
}

func RegisterOrganizationAlertServiceServer(s *grpc.Server, srv OrganizationAlertServiceServer) {
	s.RegisterService(&_OrganizationAlertService_serviceDesc, srv)
}

func _OrganizationAlertService_ListOrganizationNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrganizationNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationAlertServiceServer).ListOrganizationNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.organization_alert.OrganizationAlertService/ListOrganizationNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationAlertServiceServer).ListOrganizationNotification(ctx, req.(*ListOrganizationNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationAlertService_GetOrganizationNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrganizationNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationAlertServiceServer).GetOrganizationNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.organization_alert.OrganizationAlertService/GetOrganizationNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationAlertServiceServer).GetOrganizationNotification(ctx, req.(*GetOrganizationNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationAlertService_PutOrganizationNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutOrganizationNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationAlertServiceServer).PutOrganizationNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.organization_alert.OrganizationAlertService/PutOrganizationNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationAlertServiceServer).PutOrganizationNotification(ctx, req.(*PutOrganizationNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationAlertService_DeleteOrganizationNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrganizationNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationAlertServiceServer).DeleteOrganizationNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.organization_alert.OrganizationAlertService/DeleteOrganizationNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationAlertServiceServer).DeleteOrganizationNotification(ctx, req.(*DeleteOrganizationNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationAlertService_TestOrganizationNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestOrganizationNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationAlertServiceServer).TestOrganizationNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.organization_alert.OrganizationAlertService/TestOrganizationNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationAlertServiceServer).TestOrganizationNotification(ctx, req.(*TestOrganizationNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrganizationAlertService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "core.organization_alert.OrganizationAlertService",
	HandlerType: (*OrganizationAlertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOrganizationNotification",
			Handler:    _OrganizationAlertService_ListOrganizationNotification_Handler,
		},
		{
			MethodName: "GetOrganizationNotification",
			Handler:    _OrganizationAlertService_GetOrganizationNotification_Handler,
		},
		{
			MethodName: "PutOrganizationNotification",
			Handler:    _OrganizationAlertService_PutOrganizationNotification_Handler,
		},
		{
			MethodName: "DeleteOrganizationNotification",
			Handler:    _OrganizationAlertService_DeleteOrganizationNotification_Handler,
		},
		{
			MethodName: "TestOrganizationNotification",
			Handler:    _OrganizationAlertService_TestOrganizationNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "organization_alert/service.proto",
}
