// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/ca-risken/core/pkg/model"
)

// OrgAlertRepository is an autogenerated mock type for the OrgAlertRepository type
type OrgAlertRepository struct {
	mock.Mock
}

// DeleteOrgNotification provides a mock function with given fields: ctx, organizationID, notificationID
func (_m *OrgAlertRepository) DeleteOrgNotification(ctx context.Context, organizationID uint32, notificationID uint32) error {
	ret := _m.Called(ctx, organizationID, notificationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrgNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32) error); ok {
		r0 = rf(ctx, organizationID, notificationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrgNotification provides a mock function with given fields: ctx, organizationID, notificationID
func (_m *OrgAlertRepository) GetOrgNotification(ctx context.Context, organizationID uint32, notificationID uint32) (*model.OrganizationNotification, error) {
	ret := _m.Called(ctx, organizationID, notificationID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrgNotification")
	}

	var r0 *model.OrganizationNotification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32) (*model.OrganizationNotification, error)); ok {
		return rf(ctx, organizationID, notificationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32) *model.OrganizationNotification); ok {
		r0 = rf(ctx, organizationID, notificationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrganizationNotification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32) error); ok {
		r1 = rf(ctx, organizationID, notificationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOrgNotification provides a mock function with given fields: ctx, organizationID
func (_m *OrgAlertRepository) ListOrgNotification(ctx context.Context, organizationID uint32) ([]*model.OrganizationNotification, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListOrgNotification")
	}

	var r0 []*model.OrganizationNotification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) ([]*model.OrganizationNotification, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) []*model.OrganizationNotification); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OrganizationNotification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertOrgNotification provides a mock function with given fields: ctx, data
func (_m *OrgAlertRepository) UpsertOrgNotification(ctx context.Context, data *model.OrganizationNotification) (*model.OrganizationNotification, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpsertOrgNotification")
	}

	var r0 *model.OrganizationNotification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.OrganizationNotification) (*model.OrganizationNotification, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.OrganizationNotification) *model.OrganizationNotification); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrganizationNotification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.OrganizationNotification) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrgAlertRepository creates a new instance of OrgAlertRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrgAlertRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrgAlertRepository {
	mock := &OrgAlertRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
