name: RISKEN Core Build 
env:
  IMAGE_PREFIX: "risken-core"
  INSTALL_GO_VERSION: "1.23.3"
  GOLANGCI_LINT_VERSION: v1.62.0
  AWS_XRAY_SDK_DISABLED: TRUE
on: [push]
jobs:
  Build-Job:
    runs-on:
      - codebuild-mimosa-core-pr-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment and credentials
        run: |
          echo "SRC=${GITHUB_WORKSPACE}/src" >> $GITHUB_ENV
          echo "BUILD_OPT=--no-cache --pull" >> $GITHUB_ENV
          echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
      - name: Install Go and tools
        run: |
          cd /root/.goenv/plugins/go-build/../.. && git pull && cd -
          goenv install ${{ env.INSTALL_GO_VERSION }}
          goenv global ${{ env.INSTALL_GO_VERSION }}
          go version
          
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${{ env.GOLANGCI_LINT_VERSION }}
          mv $(go env GOPATH)/bin/golangci-lint /usr/local/bin/
          golangci-lint --version

      - name: Lint and test
        run: |
          echo "Lint the sources..."
          make lint -k
          echo "Testing the sources..."
          make test -j

      - name: Docker login and build
        if: github.event_name == 'push'
        run: |
          echo "Logging in to Amazon ECR..."
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.DOCKER_REGISTRY }}
          
          echo 'Logging in to Docker Hub...'
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          
          echo "Build gateway started on $(date)"
          make build-ci -j BUILD_OPT="${ BUILD_OPT }" IMAGE_TAG=${ TAG } IMAGE_PREFIX=${{ env.IMAGE_PREFIX }} IMAGE_REGISTRY=${{ secrets.DOCKER_REGISTRY }}
