name: RISKEN Core Build 
env:
  IMAGE_PREFIX: "risken-core"
  INSTALL_GO_VERSION: "1.23.3"
  GOLANGCI_LINT_VERSION: v1.62.0
  AWS_XRAY_SDK_DISABLED: TRUE
on: [push]
jobs:
  Build-Job:
    runs-on:
      - codebuild-mimosa-core-pr-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Go and tools
        run: |
          cd /root/.goenv/plugins/go-build/../.. && git pull && cd -
          goenv install ${{ env.INSTALL_GO_VERSION }}
          goenv global ${{ env.INSTALL_GO_VERSION }}
          go version
          
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${{ env.GOLANGCI_LINT_VERSION }}
          mv $(go env GOPATH)/bin/golangci-lint /usr/local/bin/
          golangci-lint --version


      - name: Lint and test
        run: |
          make lint -k
          make test -j