name: RISKEN Core Build PR

env:
  IMAGE_PREFIX: "risken-core"
  INSTALL_GO_VERSION: "1.23.3"
  GOLANGCI_LINT_VERSION: v1.62.0
  AWS_XRAY_SDK_DISABLED: TRUE

on: 
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
jobs:
  build_pr:
    runs-on:
      - codebuild-mimosa-core-pr-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          echo "SRC=${GITHUB_WORKSPACE}/src" >> $GITHUB_ENV
          echo "BUILD_OPT=--no-cache --pull" >> $GITHUB_ENV
          echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
      - name: Install Go and tools
        run: |
          cd /root/.goenv/plugins/go-build/../.. && git pull && cd -
          goenv install ${{ env.INSTALL_GO_VERSION }}
          goenv global ${{ env.INSTALL_GO_VERSION }}
          go version
          
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${{ env.GOLANGCI_LINT_VERSION }}
          mv $(go env GOPATH)/bin/golangci-lint /usr/local/bin/
          golangci-lint --version

      - name: Lint and test
        run: |
          echo "Lint the sources..."
          make lint -k
          echo "Testing the sources..."
          make test -j

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker build and tag
        run: |
          echo "Build gateway started on $(date)"
          make build-ci -j BUILD_OPT="${BUILD_OPT}" IMAGE_TAG=${TAG} IMAGE_PREFIX=${{ env.IMAGE_PREFIX }} IMAGE_REGISTRY=${{ secrets.DOCKER_REGISTRY }}
