syntax = "proto3";

package core.org_alert;
option go_package = "github.com/ca-risken/core/proto/org_alert";

import "google/protobuf/empty.proto";
import "org_alert/entity.proto";
import "validate/validate.proto";
import "google/protobuf/wrappers.proto";

// ListOrgNotification
message ListOrgNotificationRequest {
  uint32 organization_id = 1 [ (validate.rules).uint32.gt = 0 ];
}

message ListOrgNotificationResponse {
  repeated OrgNotification notification = 1;
}

// GetOrgNotification
message GetOrgNotificationRequest {
  uint32 organization_id = 1 [ (validate.rules).uint32.gt = 0 ];
  uint32 notification_id = 2 [ (validate.rules).uint32.gt = 0 ];
}

message GetOrgNotificationResponse { OrgNotification notification = 1; }

// PutOrgNotification
message PutOrgNotificationRequest {
  uint32 organization_id = 1 [ (validate.rules).uint32.gt = 0 ];
  uint32 notification_id = 2;
  string name = 3 [ (validate.rules).string = {min_len : 1, max_len : 200} ];
  string type = 4 [ (validate.rules).string = {min_len : 1, max_len : 64} ];
  string notify_setting = 5 [ (validate.rules).string.min_len = 1 ];
}

message PutOrgNotificationResponse { OrgNotification notification = 1; }

// DeleteOrgNotification
message DeleteOrgNotificationRequest {
  uint32 organization_id = 1 [ (validate.rules).uint32.gt = 0 ];
  uint32 notification_id = 2 [ (validate.rules).uint32.gt = 0 ];
}

// ListOrgNotificationByProject
message ListOrgNotificationByProjectRequest {
  uint32 project_id = 1 [ (validate.rules).uint32.gt = 0 ];
}

message ListOrgNotificationByProjectResponse {
  repeated OrgNotification notification = 1;
}

// TestOrgNotification
message TestOrgNotificationRequest {
  uint32 organization_id = 1 [ (validate.rules).uint32.gt = 0 ];
  uint32 notification_id = 2 [ (validate.rules).uint32.gt = 0 ];
}

// ListOrgAlertCondNotification
message ListOrgAlertCondNotificationRequest {
  uint32 organization_id = 1 [ (validate.rules).uint32.gt = 0 ];
  uint32 project_id = 2;
  uint32 alert_condition_id = 3;
  uint32 notification_id = 4;
  uint32 page_size = 5 [ (validate.rules).uint32.lte = 1000 ];
  uint32 page_offset = 6;
}

message ListOrgAlertCondNotificationResponse {
  repeated OrgAlertCondNotification alert_cond_notification = 1;
  bool has_next = 2;
  uint32 next_page_offset = 3;
}

// GetOrgAlertCondNotification
message GetOrgAlertCondNotificationRequest {
  uint32 organization_id = 1 [ (validate.rules).uint32.gt = 0 ];
  uint32 project_id = 2 [ (validate.rules).uint32.gt = 0 ];
  uint32 alert_condition_id = 3 [ (validate.rules).uint32.gt = 0 ];
  uint32 notification_id = 4 [ (validate.rules).uint32.gt = 0 ];
}

message GetOrgAlertCondNotificationResponse {
  OrgAlertCondNotification alert_cond_notification = 1;
}

// UpdateOrgAlertCondNotificationCache
message UpdateOrgAlertCondNotificationCacheRequest {
  uint32 organization_id = 1 [ (validate.rules).uint32.gt = 0 ];
  uint32 project_id = 2 [ (validate.rules).uint32.gt = 0 ];
  uint32 alert_condition_id = 3 [ (validate.rules).uint32.gt = 0 ];
  uint32 notification_id = 4 [ (validate.rules).uint32.gt = 0 ];
  google.protobuf.UInt32Value cache_second = 5
      [ (validate.rules).message.required = true, (validate.rules).uint32.lte = 31536000 ];
}

message UpdateOrgAlertCondNotificationCacheResponse {
  OrgAlertCondNotification alert_cond_notification = 1;
}

// UpdateOrgAlertProjectNotificationEnabled
message UpdateOrgAlertProjectNotificationEnabledRequest {
  uint32 organization_id = 1 [ (validate.rules).uint32.gt = 0 ];
  uint32 project_id = 2 [ (validate.rules).uint32.gt = 0 ];
  uint32 notification_id = 3 [ (validate.rules).uint32.gt = 0 ];
  google.protobuf.BoolValue enabled = 4 [ (validate.rules).message.required = true ];
}

message UpdateOrgAlertProjectNotificationEnabledResponse {
  repeated OrgAlertCondNotification alert_cond_notification = 1;
}

// UpdateOrgAlertProjectNotificationCache
message UpdateOrgAlertProjectNotificationCacheRequest {
  uint32 organization_id = 1 [ (validate.rules).uint32.gt = 0 ];
  uint32 project_id = 2 [ (validate.rules).uint32.gt = 0 ];
  uint32 notification_id = 3 [ (validate.rules).uint32.gt = 0 ];
  google.protobuf.UInt32Value cache_second = 4
      [ (validate.rules).message.required = true, (validate.rules).uint32.lte = 31536000 ];
}

message UpdateOrgAlertProjectNotificationCacheResponse {
  repeated OrgAlertCondNotification alert_cond_notification = 1;
}

// OrgAlertService
service OrgAlertService {
  rpc ListOrgNotification(ListOrgNotificationRequest)
      returns (ListOrgNotificationResponse) {}
  rpc ListOrgNotificationByProject(ListOrgNotificationByProjectRequest)
      returns (ListOrgNotificationByProjectResponse) {}
  rpc GetOrgNotification(GetOrgNotificationRequest)
      returns (GetOrgNotificationResponse) {}
  rpc PutOrgNotification(PutOrgNotificationRequest)
      returns (PutOrgNotificationResponse) {}
  rpc DeleteOrgNotification(DeleteOrgNotificationRequest)
      returns (google.protobuf.Empty) {}
  rpc TestOrgNotification(TestOrgNotificationRequest)
      returns (google.protobuf.Empty) {}
  rpc ListOrgAlertCondNotification(ListOrgAlertCondNotificationRequest)
      returns (ListOrgAlertCondNotificationResponse) {}
  rpc GetOrgAlertCondNotification(GetOrgAlertCondNotificationRequest)
      returns (GetOrgAlertCondNotificationResponse) {}
  rpc UpdateOrgAlertCondNotificationCache(
      UpdateOrgAlertCondNotificationCacheRequest)
      returns (UpdateOrgAlertCondNotificationCacheResponse) {}
  rpc UpdateOrgAlertProjectNotificationEnabled(
      UpdateOrgAlertProjectNotificationEnabledRequest)
      returns (UpdateOrgAlertProjectNotificationEnabledResponse) {}
  rpc UpdateOrgAlertProjectNotificationCache(
      UpdateOrgAlertProjectNotificationCacheRequest)
      returns (UpdateOrgAlertProjectNotificationCacheResponse) {}
}
